### ISSUE TITLE
function and type constraints

### ISSUE THREAD

**Issue by frabbit** [soywiz/hxlanguageservices#19]
it seems that function constraints are not supported at the moment.

``` haxe
interface X {}

class Test1<T:({}, X)> {}

class Test2<T:{}> {}

class F {
    static function foo <T:{}>() {}
    static function foo2<T:({}, X)>() {}
}

class Test { static function main () {}}
```

in action:
http://try.haxe.org/#DD44A

**Comment by zjnue** [comment]
Hi. If you compile and run the latest code, it should work if you replace the "object type" {} with Y in your example. Right now, it does not seem like {} is parsed as a valid "object type".

**Comment by soywiz** [comment]
This is completely fixed? Or should I reopen it? It was closed because the "fixes #19" string in commit. But not sure if fixed. I have updated the live page the last commit so you can check:  http://soywiz.github.io/hxlanguageservices/

**Comment by zjnue** [comment]
The code provided by @frabbit parses fine yes (I do check locally also). What happens after parsing I'm not considering yet. No extra type added as such. Also, I did not know the "fixes #19" commit string causes an auto-close. Will add the number only in future to allow manual inspection first.

**Comment by zjnue** [comment]
Sorry @frabbit I think the message was addressed to you. Please let us know if there are still issues with this.

**Comment by soywiz** [comment]
@zjnue No, it's ok. I have tested right now, and the example he put already parses fine.
There is no generic/constraint checking at all and it will take a while for that. So it's ok :) He would reopen it if has some examples that doesn't work. Thanks for the PR!

**Comment by frabbit** [comment]
great, thx

**Comment by zjnue** [comment]
No problem, thanks for reporting!
