### ISSUE TITLE
String support

### ISSUE THREAD

**Issue by soywiz** [soywiz/hxlanguageservices#4]
Currently parser doesn't support strings at all. So a first step is to support double quote strings, then escape sequences, then support single quote string that are a bit harder because of the string interpolation.

**Comment by soywiz** [comment]
Spaces are ignored between single-quotes strings interpolations, because of the skipNonGrammar method. We should skip the skipNonGrammar or create local skipNonGrammars for some grammar subtrees.

**Comment by soywiz** [comment]
And with that, this issue is completed (as far as I know), feel free to reopen it if you are reading it and found a case not covered here.

**Comment by zjnue** [comment]
Well done! This was no easy task and the results are amazing, and very useful!
